export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: '#333', color: '#fff', padding: '1rem', textAlign: 'center' }}>
          <h1>Welcome to Next.js</h1>
        </header>

        <main>{children}</main>
        
        <footer style={{ backgroundColor: '#333', color: '#fff', padding: '1rem', textAlign: 'center', marginTop: 'auto' }}>
          <p>&copy; 2023 Next.js Demo</p>
        </footer>
      </body>
    </html>
  );
}
