import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// this variable is used in _document.js
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


//the children prop is the content of the page
export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
